library(tidyverse)
library(purrr)
library(lubridate)
library(rlang)

#' @import tidyverse


#referenceDate <-"2022-08-07 07:00:00 EDT"
#' interval_rolling: calculates the windows for the intervals upon which to summarize. Passed to summarize_rolling
#'
#' @param referenceDate The date to start the window/interval calculation
#' @param numPeriods The number of periods to use
#' @param windowSize The width of each calculation window
#' @param windowFrequency The frequency of each calculation window
#'
#' @export
#' @return A list of intervals
#'
#' @examples NA
interval_rolling <- function(referenceDate, numPeriods, windowSize, windowFrequency) {

  periods <- seq(0, numPeriods - 1)
  endDates <- referenceDate - windowFrequency * periods


  rollingInterval <- interval(endDates - windowSize ,endDates, tzone="America/New_York")
  return(rollingInterval)
}





#' Title
#'
#' @param .data The data passed through dplyr
#' @param .interval An interval generated by interval_rolling
#' @param na.rm Remove data in summarize?
#' @param datevar The variable in .data that stores date information
#' @param groupvar The variable in .data that is used for grouping
#' @param summvar The variable in .data that is used for summarization
#' @param summfunction The function to apply to summvar
#' @param ...
#'
#' @return Data
#' @export
#'
#' @examples NA
summarize_rolling<-function(.data, .interval, na.rm=TRUE, .datevar, .groupvar, .summvar, .summfunction, ...) {
  # add grouping variable (!), change var to summary variable (!), add a function to summarise with (!).
  #intervalNames <- as.character(.interval$start + .interval$.Data)


  filter_args <- enquos(...)

  #(map_dfr(.interval, ~ (.data %>% filter({{.datevar}} %within% .x) %>% filter(str_detect(AllDispositions, "TX"), str_detect(Callsign, "MU|RU")) %>% group_by({{.groupvar}}) %>% summarise("{as.character(.x$start + .x$.Data)}" := {{.summfunction}}({{.summvar}}, na.rm=TRUE)) )) %>% pivot_longer(!{{.groupvar}}, names_to="Date", values_to="mean", values_drop_na=TRUE) %>% pivot_wider(names_from="Date", values_from="mean"))
  (map_dfr(.interval, ~ (.data %>% filter({{.datevar}} %within% .x) %>% filter(!!!filter_args) %>% group_by({{.groupvar}}) %>% summarise("{as.character(.x$start + .x$.Data)}" := {{.summfunction}}({{.summvar}}, na.rm=TRUE)) )) %>% pivot_longer(!{{.groupvar}}, names_to="Date", values_to="mean", values_drop_na=TRUE) %>% pivot_wider(names_from="Date", values_from="mean"))


  # this works instead of the longer->wider: test5 %>% group_by(Callsign) %>% summarise_all(list(~ sum(., na.rm = T)))
}
